### ISSUE TITLE
com.esotericsoftware.kryo not exist

### ISSUE THREAD

**Issue by Endle** [nielsbasjes/MavenizePig#1]
Fix: replace `com.esotericsoftware.kryo` with `com.esotericsoftware`
Ref: https://mvnrepository.com/artifact/com.esotericsoftware/kryo/3.0.3

**Comment by nielsbasjes** [comment]
Since Apache Pig is currently "almost dead" I have chosen not to continue this effort.
I you want then please copy this code (it is Apache licensed) and continue on your own.
I'm closing this and archiving this project (so you can still read it if you like).
